# Generated by Django 3.2 on 2023-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
