# Generated by Django 3.2 on 2023-03-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230304_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.BigIntegerField(default=1000000),
        ),
    ]
